"""initial_schema

Revision ID: e8d4f5814200
Revises: 
Create Date: 2026-05-21 14:15:23.128577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d4f5814200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('task', sa.Enum('segment', 'transcribe', 'binarize', name='inference_task'), nullable=False),
    sa.Column('artifact_ref', sa.String(length=1024), nullable=False),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_models')),
    sa.UniqueConstraint('name', name=op.f('uq_inference_models_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('workflow', sa.Enum('draft', 'published', 'archived', name='document_workflow'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('project_shared_users',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_shared_users_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_shared_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_shared_users'))
    )
    op.create_table('document_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_parts_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_parts'))
    )
    op.create_index(op.f('ix_document_parts_document_id'), 'document_parts', ['document_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('box', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_geometry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['document_parts.id'], name=op.f('fk_blocks_part_id_document_parts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks'))
    )
    op.create_index(op.f('ix_blocks_part_id'), 'blocks', ['part_id'], unique=False)
    op.create_table('model_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.Enum('segment', 'transcribe', 'binarize', name='binding_task'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_part_id', sa.UUID(), nullable=True),
    sa.Column('overrides', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_model_bindings_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_part_id'], ['document_parts.id'], name=op.f('fk_model_bindings_document_part_id_document_parts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['inference_models.id'], name=op.f('fk_model_bindings_model_id_inference_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_model_bindings_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_bindings'))
    )
    op.create_index(op.f('ix_model_bindings_document_id'), 'model_bindings', ['document_id'], unique=False)
    op.create_index(op.f('ix_model_bindings_document_part_id'), 'model_bindings', ['document_part_id'], unique=False)
    op.create_index(op.f('ix_model_bindings_model_id'), 'model_bindings', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_bindings_project_id'), 'model_bindings', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('segment', 'transcribe', 'binarize', 'pipeline', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='job_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('binding_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_part_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['binding_id'], ['model_bindings.id'], name=op.f('fk_jobs_binding_id_model_bindings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_jobs_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_part_id'], ['document_parts.id'], name=op.f('fk_jobs_document_part_id_document_parts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['inference_models.id'], name=op.f('fk_jobs_model_id_inference_models'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_jobs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mask', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manual_geometry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name=op.f('fk_lines_block_id_blocks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['document_parts.id'], name=op.f('fk_lines_part_id_document_parts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lines'))
    )
    op.create_index(op.f('ix_lines_block_id'), 'lines', ['block_id'], unique=False)
    op.create_index(op.f('ix_lines_part_id'), 'lines', ['part_id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('ground_truth', 'model', name='transcription_kind'), nullable=False),
    sa.Column('created_by_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_job_id'], ['jobs.id'], name=op.f('fk_transcriptions_created_by_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_transcriptions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcriptions'))
    )
    op.create_index(op.f('ix_transcriptions_document_id'), 'transcriptions', ['document_id'], unique=False)
    op.create_index('uq_transcriptions_one_ground_truth', 'transcriptions', ['document_id'], unique=True, postgresql_where="kind = 'ground_truth'")
    op.create_table('line_transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('transcription_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], name=op.f('fk_line_transcriptions_line_id_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], name=op.f('fk_line_transcriptions_transcription_id_transcriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_transcriptions')),
    sa.UniqueConstraint('line_id', 'transcription_id', name='uq_line_transcriptions_line_layer')
    )
    op.create_index(op.f('ix_line_transcriptions_line_id'), 'line_transcriptions', ['line_id'], unique=False)
    op.create_index(op.f('ix_line_transcriptions_transcription_id'), 'line_transcriptions', ['transcription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_transcriptions_transcription_id'), table_name='line_transcriptions')
    op.drop_index(op.f('ix_line_transcriptions_line_id'), table_name='line_transcriptions')
    op.drop_table('line_transcriptions')
    op.drop_index('uq_transcriptions_one_ground_truth', table_name='transcriptions', postgresql_where="kind = 'ground_truth'")
    op.drop_index(op.f('ix_transcriptions_document_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_lines_part_id'), table_name='lines')
    op.drop_index(op.f('ix_lines_block_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_model_bindings_project_id'), table_name='model_bindings')
    op.drop_index(op.f('ix_model_bindings_model_id'), table_name='model_bindings')
    op.drop_index(op.f('ix_model_bindings_document_part_id'), table_name='model_bindings')
    op.drop_index(op.f('ix_model_bindings_document_id'), table_name='model_bindings')
    op.drop_table('model_bindings')
    op.drop_index(op.f('ix_blocks_part_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_document_parts_document_id'), table_name='document_parts')
    op.drop_table('document_parts')
    op.drop_table('project_shared_users')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('inference_models')
    # ### end Alembic commands ###
