# @package sweep

experiments:
  base_random_full:
    encoder.name: base
    model.name: microsoft/trocr-base-handwritten
    model.checkpoint_dir: trocr_checkpoints/trocr-base-handwritten
    model.freeze_encoder: false
    decoder.reinitialize: all
    lora_adaptors.enabled: false
  base_pretrained_decoder:
    encoder.name: base
    model.name: microsoft/trocr-base-handwritten
    model.checkpoint_dir: trocr_checkpoints/trocr-base-handwritten
    model.freeze_encoder: true
    decoder.reinitialize: token_layers
    lora_adaptors.enabled: false
  base_pretrained_lora:
    encoder.name: base
    model.name: microsoft/trocr-base-handwritten
    model.checkpoint_dir: trocr_checkpoints/trocr-base-handwritten
    model.freeze_encoder: true
    decoder.reinitialize: token_layers
    lora_adaptors.enabled: true
  base_pretrained_full:
    encoder.name: base
    model.name: microsoft/trocr-base-handwritten
    model.checkpoint_dir: trocr_checkpoints/trocr-base-handwritten
    model.freeze_encoder: false
    decoder.reinitialize: token_layers
    lora_adaptors.enabled: false
  base_random_lora:
    encoder.name: base
    model.name: microsoft/trocr-base-handwritten
    model.checkpoint_dir: trocr_checkpoints/trocr-base-handwritten
    model.freeze_encoder: true
    decoder.reinitialize: all
    lora_adaptors.enabled: true
