name: trocr-encoder-decoder-ablation
project: OCR
entity: personal-space-astha
method: grid

metric:
  name: eval/cer
  goal: minimize

program: src.train.trocr
command:
  - ${env}
  - ${interpreter}
  - -m
  - src.train.trocr
  - wandb.enabled=true
  - wandb.name=null
  - training.epochs=40
  - training.checkpoint_top_k=1

parameters:
  experiment:
    values:
      - small_random_full
      - small_pretrained_decoder
      - small_pretrained_lora
      - small_pretrained_full
      - small_random_lora
      - base_random_full
      - base_pretrained_decoder
      - base_pretrained_lora
      - base_pretrained_full
      - base_random_lora
