# @package _global_

model:
  name: microsoft/trocr-small-handwritten
  checkpoint_dir: trocr_checkpoints/trocr-small-handwritten
  freeze_encoder: false

training:
  epochs: 100
  batch_size: 32
  eval_batch_size: 32
  gradient_accumulation_steps: 1
  save_strategy: epoch
  checkpoint_top_k: 2
  num_workers: 4
  seed: 1111
  max_steps: -1
  no_fp16: false
