defaults:
  - data: default
  - model: default
  - augmentation: default
  - training: default
  - optimizer: default
  - logging: default
  - logging@wandb: wand
  - output: default
  - evaluation: default
  - preparation: default
  - _self_

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
