defaults:
  - data: pretraining/combined
  - model: default
  - augmentation: default
  - training: pretraining
  - optimizer: default
  - logging: default
  - logging@wandb: wand
  - output: default
  - evaluation: default
  - preparation: default
  - _self_

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
