/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pages */
        get: operations["get_pages_pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Import Page */
        post: operations["post_import_page_pages_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Image */
        get: operations["get_page_image_pages__stem__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcription */
        get: operations["get_transcription_pages__stem__transcription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/annotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Annotation */
        get: operations["get_annotation_pages__stem__annotation_get"];
        /** Put Annotation */
        put: operations["put_annotation_pages__stem__annotation_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/binarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Binarize Page
         * @description Binarize the whole page with Kraken nlbin and use it for display and processing.
         */
        post: operations["post_binarize_page_pages__stem__binarize_post"];
        /**
         * Delete Binarized Page
         * @description Revert to the original manuscript image for display and processing.
         */
        delete: operations["delete_binarized_page_pages__stem__binarize_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Auto Segment
         * @description Run Kraken BLLA line segmentation and save segments to the page annotation JSON.
         */
        post: operations["post_auto_segment_pages__stem__segment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Lock Page */
        post: operations["post_lock_page_pages__stem__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Unlock Page */
        post: operations["post_unlock_page_pages__stem__unlock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page History */
        get: operations["get_page_history_pages__stem__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/history/{snapshot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Restore History */
        post: operations["post_restore_history_pages__stem__history__snapshot_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/transcription.share.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcription Share Pdf */
        get: operations["get_transcription_share_pdf_pages__stem__transcription_share_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/transcription.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcription Pdf */
        get: operations["get_transcription_pdf_pages__stem__transcription_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/segments/{segment_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Segment Preview */
        get: operations["get_segment_preview_pages__stem__segments__segment_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/segments/{segment_id}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Segment Ocr
         * @description Run Calamari OCR on one segment and persist model transcription fields.
         */
        post: operations["post_segment_ocr_pages__stem__segments__segment_id__ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/ocr/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Page Ocr Stream
         * @description Stream NDJSON progress while running OCR on every segment on the page.
         */
        post: operations["post_page_ocr_stream_pages__stem__ocr_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Export */
        post: operations["post_export_pages__stem__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{stem}/export/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Export Stream */
        post: operations["post_export_stream_pages__stem__export_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AutoSegmentRequest
         * @description Run Kraken line segmentation on a page image.
         */
        AutoSegmentRequest: {
            /**
             * Replace
             * @description Replace existing segments. If false, append Kraken lines after current segments.
             * @default true
             */
            replace: boolean;
            /**
             * Pair Transcription
             * @description Pair segments to transcription text lines in reading order when available.
             * @default true
             */
            pair_transcription: boolean;
        };
        /** Body_post_import_page_pages_import_post */
        Body_post_import_page_pages_import_post: {
            /** Image */
            image: string;
            /** Transcription */
            transcription?: string | null;
        };
        /** ExportMetadata */
        ExportMetadata: {
            /** Exported At */
            exported_at: string;
            /** Content Hash */
            content_hash: string;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Exported Count */
            exported_count: number;
            warnings: components["schemas"]["ExportWarnings"];
            /** Steps */
            steps: string[];
        };
        /** ExportWarnings */
        ExportWarnings: {
            /** Unpaired Segments */
            unpaired_segments: number[];
            /** Unused Text Lines */
            unused_text_lines: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** HistoryListResponse */
        HistoryListResponse: {
            /** Snapshots */
            snapshots: components["schemas"]["HistorySnapshotSummary"][];
        };
        /** HistorySnapshotSummary */
        HistorySnapshotSummary: {
            /** Id */
            id: string;
            /** Timestamp */
            timestamp: string;
            /** Reason */
            reason: string;
            /** Pairing Progress Percent */
            pairing_progress_percent: number;
        };
        /** ModelCharacterConfidence */
        ModelCharacterConfidence: {
            /** Char */
            char: string;
            /** Probability */
            probability: number;
        };
        /** PageAnnotation */
        PageAnnotation: {
            /** Segments */
            segments?: components["schemas"]["Segment"][];
            export_metadata?: components["schemas"]["ExportMetadata"] | null;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Binarized At */
            binarized_at?: string | null;
        };
        /** PageListResponse */
        PageListResponse: {
            /** Pages */
            pages: components["schemas"]["PageSummary"][];
        };
        /** PageSummary */
        PageSummary: {
            /** Stem */
            stem: string;
            /** Has Transcription */
            has_transcription: boolean;
            /** Segment Count */
            segment_count: number;
            /** Export Dirty */
            export_dirty: boolean;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            pairing: components["schemas"]["PairingProgress"];
        };
        /** PairingProgress */
        PairingProgress: {
            /** Paired Count */
            paired_count: number;
            /** Unpaired Count */
            unpaired_count: number;
            /** Text Line Count */
            text_line_count: number;
            /** Unused Line Count */
            unused_line_count: number;
        };
        /** Segment */
        Segment: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "polygon" | "rectangle";
            /** Points */
            points: number[][];
            /** Paired Text Line Index */
            paired_text_line_index?: number | null;
            /** Text Override */
            text_override?: string | null;
            /** Model Transcription */
            model_transcription?: string | null;
            /** Model Transcription Confidence */
            model_transcription_confidence?: components["schemas"]["ModelCharacterConfidence"][] | null;
            /** Model Transcription At */
            model_transcription_at?: string | null;
            /**
             * Source
             * @default manual
             * @enum {string}
             */
            source: "manual" | "kraken";
            /** Kraken Ceiling */
            kraken_ceiling?: number[][] | null;
        };
        /** TextLineOut */
        TextLineOut: {
            /** Index */
            index: number;
            /** Text */
            text: string;
        };
        /** TranscriptionResponse */
        TranscriptionResponse: {
            /** Raw Text */
            raw_text: string | null;
            /** Text Lines */
            text_lines: components["schemas"]["TextLineOut"][];
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_pages_pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponse"];
                };
            };
        };
    };
    post_import_page_pages_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_import_page_pages_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_image_pages__stem__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcription_pages__stem__transcription_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_annotation_pages__stem__annotation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_annotation_pages__stem__annotation_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageAnnotation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_binarize_page_pages__stem__binarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_binarized_page_pages__stem__binarize_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_auto_segment_pages__stem__segment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AutoSegmentRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_lock_page_pages__stem__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_unlock_page_pages__stem__unlock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_history_pages__stem__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_restore_history_pages__stem__history__snapshot_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcription_share_pdf_pages__stem__transcription_share_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcription_pdf_pages__stem__transcription_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_preview_pages__stem__segments__segment_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_segment_ocr_pages__stem__segments__segment_id__ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAnnotation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_page_ocr_stream_pages__stem__ocr_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_export_pages__stem__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_export_stream_pages__stem__export_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stem: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
