defaults:
  - training: default
  - optimizer: default
  - logging: default
  - logging@wandb: wand
  - output: local
  - tokenizer: gpt_new
  - decoder: decoder
  - lora_adaptors: lora
  - augmentation: default
  - evaluation: default
  - preparation: default
  - _self_

data:
  dir: data/trocr_processed/combined/pretraining

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
